//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaAFP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusSalary
    {
        public int ID { get; set; }
        public int IdEmployee { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Employee employee { get; set; }
    }
}
