//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaAFP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionFinance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConditionFinance()
        {
            this.recommendations = new HashSet<Recommendation>();
        }
    
        public int ID { get; set; }
        public Nullable<sbyte> IsPredictedProfitNegative { get; set; }
        public Nullable<sbyte> IsWorkingCapitalNotEnough { get; set; }
        public Nullable<sbyte> IsWorkingCapitalEnoughSalary { get; set; }
        public Nullable<sbyte> IsWokingCapitalEnoughMaterial { get; set; }
        public Nullable<sbyte> IsWorkingCapitalEnoughFixedCosts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recommendation> recommendations { get; set; }
    }
}
