//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaAFP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.contract_payments = new HashSet<ContractPayment>();
        }
    
        public int ID { get; set; }
        public int IdOrder { get; set; }
        public System.DateTime DateSigning { get; set; }
        public decimal Price { get; set; }
        public decimal Prepayment { get; set; }
        public int ProductionDays { get; set; }
        public string ProjectTitle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractPayment> contract_payments { get; set; }
        public virtual Order order { get; set; }
    }
}
