//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaAFP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyCost
    {
        public int ID { get; set; }
        public int IdFixedCost { get; set; }
        public int DayAccrual { get; set; }
    
        public virtual FixedCost fixed_costs { get; set; }
    }
}
