//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaAFP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationProduct
    {
        public int ID { get; set; }
        public int IdOperation { get; set; }
        public int IdProduct { get; set; }
        public int Quantity { get; set; }
    
        public virtual ManufacturingOperation manufacturing_operations { get; set; }
        public virtual Product product { get; set; }
    }
}
