//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaAFP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteOffMaterial
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int IdMaterial { get; set; }
        public int QuantityUnits { get; set; }
    
        public virtual Material material { get; set; }
    }
}
